name: Lint Javascript Code

on:
  push:
  pull_request:

permissions:
  checks: write
  contents: write
  
jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.STARTER_APP_ID}}
          private-key: ${{ secrets.STARTER_PRIVATE_KEY }}
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 14.x
      - name: Install Node.js dependencies
        run: npm ci
      - name: Run linters
        uses: super-linter/super-linter@v8.1.0
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          ENABLE_GITHUB_ACTIONS_STEP_SUMMARY: true
          SAVE_SUPER_LINTER_OUTPUT: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          FIX_JAVASCRIPT_ES: true
          FIX_TYPESCRIPT_ES: true
          FIX_JSON: true
          FIX_MARKDOWN: true
          FIX_YAML: true
