
name: Node.js CI - with cache - composite

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v5
    - uses: ./.github/actions/build-node